apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingapp-deploy
  labels:
    app: bankingapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankingapp-app
  template:
    metadata:
      labels:
        app: bankingapp-app
    spec:
      containers:
      - name: bankingapp-container
        image: devsaikiran24/bankingapp-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankingapp-np-service
  labels:
    app: bankingapp-app
spec:
  selector:
    app: bankingapp-app

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
